name: mkdocs-pages
on:
  workflow_call:
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      # Checkout repo to GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install Python
      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.x

      # Install PyPI packages
      - name: Dependencies
        run: pip install -r requirements.txt

      # Push to GitHub Pages
      - name: Push Docs
        run: |
          mkdocs gh-deploy --force
